spring:
  datasource:
    druid:
      url: jdbc:oracle:thin:@192.168.1.206:1521:orcl
      username: yt_dms
      password: yt_dms

  redis:
    password:
    host: 127.0.0.1
    port: 6379

#    timeout: 6000ms
#    lettuce:
#      pool:
#        max-active: 1000
#        max-idle: 10
#        min-idle: 5
#        max-wait: -1
#    cluster:
#      nodes:
#        - 127.0.0.1:6379
#        - 192.168.1.50:6379
#      max-redirects: 3
