server:
  port: 8808

spring:
  application:
    name: cc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      default-filters:  # 全局断路器
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallbackcontroller

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
